name: Terraform GCP Deployment

on:    
  workflow_dispatch:
    inputs:
      environment:
        description: 'Wybierz środowisko (production)'
        required: false
        default: 'production'

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production
    concurrency: # zapobiega równoczesnemu uruchomieniu
      group: terraform-gcp-lock
      cancel-in-progress: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan -var="project_id=${{ secrets.PROJECT_ID }}" -var="region=${{ secrets.REGION }}"

      